stages:
  train:
    cmd: train.bat
    deps:
      - src/train.py
      - src/utils.py
      - src/model.py
      - data/imdb.csv
    outs:
      - model.joblib
      - vectorizer.joblib

  evaluate:
    cmd: python src/eval.py
    deps:
      - src/eval.py
      - model.joblib
      - vectorizer.joblib
      - data/imdb.csv