apiVersion: v1                          # Core K8s API
kind: Service                           # We're creating a Service resource
metadata:
  name: sentiment-api-service           # Name of the service
spec:
  selector:
    app: sentiment-api                  # Match pods with this label
  ports:
    - protocol: TCP                     # TCP is used for HTTP APIs
      port: 80                          # External port (public access)
      targetPort: 8000                  # Container's internal FastAPI port
  type: LoadBalancer                    # Creates a public-facing IP on AWS/GCP/Azure
