apiVersion: v1
kind: Secret                            # We're creating a Secret resource
metadata:
  name: aws-secrets                     # Name referenced in deployment
type: Opaque                            # Generic key-value secret (base64 encoded by default)
stringData:                             # Use stringData for plain-text values
  AWS_ACCESS_KEY_ID: your-access-key         # Replace with your real AWS access key
  AWS_SECRET_ACCESS_KEY: your-secret-key     # Replace with your AWS secret key
  AWS_DEFAULT_REGION: us-east-1              # Replace with your preferred region
  MLFLOW_TRACKING_URI: http://mlflow-service:5000  # Or remote URI if hosted externally
